# Generated by Django 6.0.3 on 2026-03-05 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddybasket', '0002_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_status',
            field=models.CharField(choices=[('none', 'No Refund'), ('processing', 'Refund Processing'), ('completed', 'Refund Completed'), ('failed', 'Refund Failed')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
