# Generated by Django 6.0.3 on 2026-03-06 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buddybasket', '0003_order_cancel_requested_order_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cancel_requested',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cancellation_reason',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cancelled_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='refund_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='refunded_at',
        ),
    ]
