# Generated by Django 6.0.3 on 2026-03-06 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddybasket', '0004_remove_order_cancel_requested_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
